In [92]:
%load_ext autoreload
%autoreload 2

In [24]:
# Imports

import os
from PIL import Image
import random
import numpy as np

In [87]:
# Set constants

audio_folderpath = "C:/Users/anany/Cambridge/Part II Project/data/raw"
image_folderpath = "C:/Users/anany\Cambridge\Part II Project\data\images"
split_ratio = 0.75
image_type = "spectrogram"
clip_length = 10
shift_length = 5
resize_dim = 129

In [88]:
# Category list

genre_id = {}


for genre in os.listdir(audio_folderpath):
    i = 1
    while (genre[:i] in genre_id.values() and i <= len(genre)):
        i += 1
    genre_id[genre] = genre[:i]

In [89]:
# Generate ids and create song dictionary

audio_dict = {}

for genre in genre_id:
    files = os.listdir(os.path.join(audio_folderpath, genre))
    count = 0
    for file in files:
        filepath = os.path.join(audio_folderpath, genre, file)
        id = genre_id[genre] + '{:03d}'.format(count)
        count += 1
        audio_dict[id] = filepath

In [90]:
# Split train/test

id_list = list(audio_dict.keys())
random.shuffle(id_list)
split_index = int(split_ratio * len(id_list))

train_set = id_list[:split_index]
test_set = id_list[split_index:]

In [93]:
from visualization_new import *


def get_image_func(image_type):
    if image_type == "spectrogram":
        return wav_to_spectrogram
    elif image_type == "chromagram":
        return wav_to_chromagram
    elif image_type == "mfcc":
        return wav_to_mfcc
    elif image_type == "cochleagram":
        return wav_to_cochleagram
    else:
        return
    

to_image = get_image_func(image_type)

In [8]:
'''cp.cuda.runtime.getDeviceCount()'''

'cp.cuda.runtime.getDeviceCount()'

# WITHOUT GENERATOR

In [94]:
'''TRAIN SET'''

train_ids = None
train_imgs = None
train_labels = None

label_list = list(genre_id.values())

count = 0
for id in train_set:
    filepath = audio_dict[id]

    # Convert to image(whole) - this is an object NOT a file
    images = to_image(filepath)

    # Feed image objects into splitting function
    for i in range(2):
        # Dictionary mapping audio sample id to audio sample data
        img_dict = split(images[i], id + "_ch" + str(i), clip_length, shift_length, resize_dim)
        
        # Set/update audio sample id list
        if train_ids is None:
            train_ids = list(img_dict.keys())
        else:
            train_ids.extend(list(img_dict.keys()))



        # Set/update array of image arrays
        if train_imgs is None:
            train_imgs = cp.array(list(img_dict.values()))
        else:
            train_imgs = cp.append(train_imgs, list(img_dict.values()), axis = 0)

        print("    ", i)
        #train_imgs.extend(list(img_dict.values()))
    print(count)
    count += 1
    
new_train_labels = np.array([label_list.index(x.split('_')[0][:-3]) for x in train_ids])
if train_labels is None:
    train_labels = new_train_labels
else:
    train_labels = cp.append(train_labels, new_train_labels, axis = 0)

        

     

    # TODO: resize, color regularize or something
#train_imgs_resized = [x.resize((resize_dim, resize_dim)) for x in train_imgs]


    

     0
     1
0
     0
     1
1
     0
     1
2
     0
     1
3
     0
     1
4
     0
     1
5
     0
     1
6
     0
     1
7
     0
     1
8
     0
     1
9
     0
     1
10
     0
     1
11
     0
     1
12
     0
     1
13
     0
     1
14
     0
     1
15
     0
     1
16
     0
     1
17
     0
     1
18
     0
     1
19
     0
     1
20
     0
     1
21
     0
     1
22
     0
     1
23
     0
     1
24
     0
     1
25
     0
     1
26
     0
     1
27
     0
     1
28
     0
     1
29
     0
     1
30
     0
     1
31
     0
     1
32
     0
     1
33
     0
     1
34
     0
     1
35
     0
     1
36


In [101]:
train_imgs[0]

array([[[0.2745098 , 0.05882353, 0.38431373, 1.        ],
        [0.28235294, 0.07058824, 0.4       , 1.        ],
        [0.24705882, 0.11764706, 0.41960784, 1.        ],
        ...,
        [0.14117647, 0.66666667, 0.50980392, 1.        ],
        [0.15294118, 0.68235294, 0.50196078, 1.        ],
        [0.28235294, 0.73333333, 0.42745098, 1.        ]],

       [[0.2745098 , 0.05490196, 0.38039216, 1.        ],
        [0.28235294, 0.06666667, 0.39607843, 1.        ],
        [0.24705882, 0.11372549, 0.41568627, 1.        ],
        ...,
        [0.14901961, 0.67058824, 0.50588235, 1.        ],
        [0.15686275, 0.68627451, 0.49803922, 1.        ],
        [0.27058824, 0.72941176, 0.43529412, 1.        ]],

       [[0.2745098 , 0.04313725, 0.37254902, 1.        ],
        [0.27843137, 0.05098039, 0.38039216, 1.        ],
        [0.25098039, 0.10588235, 0.40784314, 1.        ],
        ...,
        [0.16862745, 0.68627451, 0.49411765, 1.        ],
        [0.17647059, 0.698039

In [30]:
'''TEST SET'''

test_ids = None
test_imgs = None
test_labels = None

label_list = list(genre_id.values())

count = 0
for id in test_set:
    filepath = audio_dict[id]

    # Convert to image(whole) - this is an object NOT a file
    images = to_image(filepath)

    # Feed image objects into splitting function
    for i in range(2):
        # Dictionary mapping audio sample id to audio sample data
        img_dict = split(images[i], id + "_ch" + str(i), clip_length, shift_length, resize_dim)
        
        # Set/update audio sample id list
        if test_ids is None:
            test_ids = list(img_dict.keys())
        else:
            test_ids.extend(list(img_dict.keys()))



        # Set/update array of image arrays
        if test_imgs is None:
            test_imgs = cp.array(list(img_dict.values()))
        else:
            test_imgs = cp.append(test_imgs, list(img_dict.values()), axis = 0)

        print("    ", i)
    print(count)
    count += 1
    
new_test_labels = np.array([label_list.index(x.split('_')[0][:-3]) for x in test_ids])
if test_labels is None:
    test_labels = new_test_labels
else:
    test_labels = cp.append(test_labels, new_test_labels, axis = 0)

        

     


    

     0
     1
0
     0
     1
1
     0
     1
2
     0
     1
3
     0
     1
4
     0
     1
5
     0
     1
6
     0
     1
7
     0
     1
8
     0
     1
9
     0
     1
10
     0
     1
11
     0
     1
12


In [11]:
'''myarray = (test_imgs[10] * 255).astype(np.uint8)

Image.fromarray(np.array(myarray.get()))'''

'myarray = (test_imgs[10] * 255).astype(np.uint8)\n\nImage.fromarray(np.array(myarray.get()))'

In [12]:
'''print(len(test_ids))
print(test_labels.shape)
print(test_imgs.shape)'''

'print(len(test_ids))\nprint(test_labels.shape)\nprint(test_imgs.shape)'

In [13]:
'''myarray = train_imgs[0].shape

from PIL import Image
from matplotlib import cm
im = Image.fromarray(np.uint8(cm.gist_earth(myarray)*255))'''

'myarray = train_imgs[0].shape\n\nfrom PIL import Image\nfrom matplotlib import cm\nim = Image.fromarray(np.uint8(cm.gist_earth(myarray)*255))'

In [14]:
'''# TODO: iterate, convert, add to correct set

x_train = cp.asarray([cp.asarray(x) for x in train_imgs_resized]) / 255.0
y_train = cp.asarray(train_labels)
x_test = cp.asarray([cp.asarray(x) for x in test_imgs_resized]) / 255.0
y_test = cp.asarray(test_labels)
'''

'# TODO: iterate, convert, add to correct set\n\nx_train = cp.asarray([cp.asarray(x) for x in train_imgs_resized]) / 255.0\ny_train = cp.asarray(train_labels)\nx_test = cp.asarray([cp.asarray(x) for x in test_imgs_resized]) / 255.0\ny_test = cp.asarray(test_labels)\n'

In [15]:
'''x_train = train_imgs.get()
y_train = train_labels
x_test = test_imgs.get()
y_test = test_labels'''

'x_train = train_imgs.get()\ny_train = train_labels\nx_test = test_imgs.get()\ny_test = test_labels'

In [16]:
'''import tensorflow as tf

from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt'''

'import tensorflow as tf\n\nfrom tensorflow.keras import datasets, layers, models\nimport matplotlib.pyplot as plt'

In [17]:
'''model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=x_train[0].shape))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))'''

"model = models.Sequential()\nmodel.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=x_train[0].shape))\nmodel.add(layers.MaxPooling2D((2, 2)))\nmodel.add(layers.Conv2D(64, (3, 3), activation='relu'))\nmodel.add(layers.MaxPooling2D((2, 2)))\nmodel.add(layers.Conv2D(64, (3, 3), activation='relu'))"

In [18]:
'''model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))'''

"model.add(layers.Flatten())\nmodel.add(layers.Dense(64, activation='relu'))\nmodel.add(layers.Dense(10))"

In [19]:
'''model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(x_train, y_train, epochs=5, 
                    validation_data=(x_test, y_test))'''

"model.compile(optimizer='adam',\n              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),\n              metrics=['accuracy'])\n\nhistory = model.fit(x_train, y_train, epochs=5, \n                    validation_data=(x_test, y_test))"

# WITH GEN

In [20]:

def train_gen():

    label_list = list(genre_id.values())

    count = 0

    while True:

        for id in train_set:
            filepath = audio_dict[id]

            train_ids = None
            train_imgs = None
            train_labels = None

            # Convert to image(whole) - this is an object NOT a file
            images = to_image(filepath)

            # Feed image objects into splitting function
            for i in range(2):
                # Dictionary mapping audio sample id to audio sample data
                img_dict = split(images[i], id + "_ch" + str(i), clip_length, shift_length, resize_dim)
                
                # Set/update audio sample id list
                if train_ids is None:
                    train_ids = list(img_dict.keys())
                else:
                    train_ids.extend(list(img_dict.keys()))


                # Set/update array of image arrays
                if train_imgs is None:
                    train_imgs = np.array(list(img_dict.values()))
                else:
                    train_imgs = np.append(train_imgs, np.array(list(img_dict.values())), axis = 0)

                #print("    ", i)
                #train_imgs.extend(list(img_dict.values()))
            #print(count)
            count += 1
            
            train_labels = np.array([label_list.index(x.split('_')[0][:-3]) for x in train_ids])

            yield train_imgs, train_labels
    
        print("END TRAIN")


                


            

In [21]:
def test_gen():
    test_ids = None
    test_imgs = None
    test_labels = None

    label_list = list(genre_id.values())

    count = 0

    while True:


        for id in test_set:
            filepath = audio_dict[id]

            # Convert to image(whole) - this is an object NOT a file
            images = to_image(filepath)

            # Feed image objects into splitting function
            for i in range(2):
                # Dictionary mapping audio sample id to audio sample data
                img_dict = split(images[i], id + "_ch" + str(i), clip_length, shift_length, resize_dim)
                
                # Set/update audio sample id list
                if test_ids is None:
                    test_ids = list(img_dict.keys())
                else:
                    test_ids.extend(list(img_dict.keys()))



                # Set/update array of image arrays
                if test_imgs is None:
                    test_imgs = np.array(list(img_dict.values()))
                else:
                    test_imgs = np.append(test_imgs, np.array(list(img_dict.values())), axis = 0)

                #print("    ", i)
            #print(count)
            count += 1
            
            test_labels = np.array([label_list.index(x.split('_')[0][:-3]) for x in test_ids])

            yield test_imgs, test_labels
        
        print("END TEST")

In [22]:
import tensorflow as tf

from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(resize_dim, resize_dim, 4)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))

In [23]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(train_gen(),
                    steps_per_epoch=3,
                              epochs=8,
                              validation_data=test_gen(),
                              validation_steps=3
                              )

'''history = model.fit(x_train, y_train, epochs=5, 
                    validation_data=(x_test, y_test))'''

Epoch 1/8
3/3 [==============================] - 35s 15s/step - loss: 48.1456 - accuracy: 0.0000e+00 - val_loss: 20.3622 - val_accuracy: 0.1954
Epoch 2/8
3/3 [==============================] - ETA: 0s - loss: 7.7845 - accuracy: 0.0000e+00

# WITH PYTORCH

# MY CNN

In [34]:
from cnn.activation import Tanh, Sigmoid
from cnn.convolutional import Convolutional
from cnn.dense import Dense
from cnn.loss import MSE, MSE_prime, binary_cross_entropy, binary_cross_entropy_prime
from cnn.nn import MNIST
from cnn.reshape import Reshape

In [22]:
audio_folderpath = "C:/Users/anany/Cambridge/Part II Project/data/raw"
image_folderpath = "C:/Users/anany\Cambridge\Part II Project\data\images"
split_ratio = 0.75
image_type = "spectrogram"
clip_length = 10
shift_length = 500
resize_dim = 28

In [31]:
# train_ids
# train_imgs
# train_labels

# test_ids
# test_imgs
# test_labels

array([0, 0, 2, 2, 0, 0, 4, 4, 0, 0, 4, 4, 2, 2, 1, 1, 4, 4, 0, 0, 3, 3,
       3, 3, 1, 1])

In [63]:
temp = train_imgs.reshape((74, 1, 28, 28, 4))

temp.shape

(74, 1, 28, 28, 4)

In [ ]:
network = [
        Convolutional(input_shape=(1, 28, 28, 4), kernel_size=3, depth=5), # output_shape=()
        Sigmoid()
    ]

In [70]:
c = Convolutional(input_shape=(1, 28, 28, 4), kernel_size=3, depth=5), # output_shape=()


ValueError: too many values to unpack (expected 3)

In [ ]:
epochs = 20
learning_rate = 0.1

for e in range(epochs):
    error = 0

    temp = zip(x_train, y_train)
    for x, y in zip(x_train, y_train):
        output = x
        for layer in network:
            output = layer.forward(output)
        
        error += binary_cross_entropy(y, output)

        grad = binary_cross_entropy_prime(y, output)
        for layer in reversed(network):
            grad = layer.backward(grad, learning_rate)
    
    error /= len(x_train)
    print(f"{e + 1}/{epochs}, error = {error}")

In [71]:
MNIST()

1/20, error = 0.29174904351223846
2/20, error = 0.06523393893289796
3/20, error = 0.04482472830743084
4/20, error = 0.017893832092078333
5/20, error = 0.010019754374280758
6/20, error = 0.007956868974355146
7/20, error = 0.006365971128654754
8/20, error = 0.005518842253885437
9/20, error = 0.004870873720918497
10/20, error = 0.004377086567407643
11/20, error = 0.003980103157568912
12/20, error = 0.003652179398251721
13/20, error = 0.0033757917537399974
14/20, error = 0.003139399227425653
15/20, error = 0.00293487950356693
16/20, error = 0.0027562031446883035
17/20, error = 0.002598730915025944
18/20, error = 0.0024588323912226825
19/20, error = 0.0023336445914558137
20/20, error = 0.0022208939011593145
pred: 1, true: 1
pred: 0, true: 0
pred: 1, true: 1
pred: 1, true: 1
pred: 0, true: 0
pred: 1, true: 1
pred: 0, true: 0
pred: 1, true: 1
pred: 1, true: 1
pred: 0, true: 0
pred: 0, true: 0
pred: 0, true: 0
pred: 1, true: 1
pred: 1, true: 1
pred: 0, true: 0
pred: 1, true: 1
pred: 1, true: 1

In [83]:
arr = np.array([[[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]], [[0, 1, 2, 3], [0, 1, 2, 3], [0, 1, 2, 3]]])
# 2 3 4

new_arr = np.moveaxis(arr, 2, 0)
# 4 3 2

new_arr[:3]

array([[[0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [86]:
arr

array([[[0.2627451 , 0.30588235, 0.40784314, 1.        ],
        [0.29803922, 0.74117647, 0.42745098, 1.        ],
        [0.30196078, 0.7254902 , 0.42745098, 1.        ],
        ...,
        [0.34117647, 0.77647059, 0.39607843, 1.        ],
        [0.21176471, 0.71372549, 0.47058824, 1.        ],
        [0.18431373, 0.69411765, 0.48627451, 1.        ]],

       [[0.21176471, 0.25098039, 0.41960784, 1.        ],
        [0.11372549, 0.58431373, 0.55294118, 1.        ],
        [0.14509804, 0.58431373, 0.53333333, 1.        ],
        ...,
        [0.21176471, 0.70980392, 0.47058824, 1.        ],
        [0.17647059, 0.6745098 , 0.49411765, 1.        ],
        [0.14509804, 0.63921569, 0.51764706, 1.        ]],

       [[0.21568627, 0.23921569, 0.42352941, 1.        ],
        [0.13333333, 0.55686275, 0.55686275, 1.        ],
        [0.14901961, 0.56862745, 0.53333333, 1.        ],
        ...,
        [0.12156863, 0.57647059, 0.54901961, 1.        ],
        [0.1254902 , 0.564705

In [85]:
arr = train_imgs[0]

new_arr = np.moveaxis(arr, -1, 0)

new_arr

array([[[0.2627451 , 0.29803922, 0.30196078, ..., 0.34117647,
         0.21176471, 0.18431373],
        [0.21176471, 0.11372549, 0.14509804, ..., 0.21176471,
         0.17647059, 0.14509804],
        [0.21568627, 0.13333333, 0.14901961, ..., 0.12156863,
         0.1254902 , 0.1254902 ],
        ...,
        [0.26666667, 0.26666667, 0.26666667, ..., 0.2627451 ,
         0.26666667, 0.26666667],
        [0.26666667, 0.26666667, 0.26666667, ..., 0.26666667,
         0.26666667, 0.26666667],
        [0.26666667, 0.26666667, 0.26666667, ..., 0.26666667,
         0.26666667, 0.26666667]],

       [[0.30588235, 0.74117647, 0.7254902 , ..., 0.77647059,
         0.71372549, 0.69411765],
        [0.25098039, 0.58431373, 0.58431373, ..., 0.70980392,
         0.6745098 , 0.63921569],
        [0.23921569, 0.55686275, 0.56862745, ..., 0.57647059,
         0.56470588, 0.56470588],
        ...,
        [0.03921569, 0.01176471, 0.01960784, ..., 0.02352941,
         0.01176471, 0.05882353],
        [0.0